language: php
sudo: required
addons:
  apt:
    packages:
    - ca-certificates
    - unzip
    - curl
    - ntp
    - apache2
    - php5
    - libapache2-mod-php5
    - php5-cli
    - php5-common
    - php5-curl
    - php5-fpm
    - php5-json
    - php5-mysql
    - php5-gd
php:
  - 5.6
  - 7.0
install:
  - sudo chmod +x install/install_deps.sh
  - sudo ./install/install_deps.sh travis
  - php install/install.php mode=force
  - sudo mkdir /home/travis/build/jeedom/plugins
  - sudo chmod 777 -R /home/travis/build/jeedom
  - sudo chown www-data:www-data -R /home/travis/build/jeedom