language: php
sudo: required
php:
  - 5.6
  - 7.0
install:
  - sudo chmod +x install/travis.sh
  - sudo install/travis.sh
  - php install/install.php mode=force
  - sudo chmod 777 -R /home/travis/build/jeedom
  - sudo chown www-data:www-data -R /home/travis/build/jeedom